### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by punitganshani** [j3lte/node-ifttt-maker#1]
Hi,

Getting following error with the sample source code provided. Please check

```
root@galileo:~/code/connectivity# node connectivity.js

/home/root/code/connectivity/node_modules/node-ifttt-maker/node_modules/request/node_modules/tough-cookie/lib/pubsuffix.js:96
es-ghc29a.museum":true,"corvette.museum":true,"costume.museum":true,"countryes
                                                                    ^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/root/code/connectivity/node_modules/node-ifttt-maker/node_modules/request/node_modules/tough-cookie/lib/cookie.js:34:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by j3lte** [comment]
You'll have to check the parameters you're providing. Seems there might be some illegal characters in it. Can you provide a snippet of the code where you use node-ifttt-maker, and a sample of the parameters?

**Comment by j3lte** [comment]
It relates to this code https://github.com/SalesforceEng/tough-cookie/blob/master/lib/pubsuffix.js#L96

So it might not have anything to do with your code. Can you tell me what version of Node you are using? I might have to update the request module

**Comment by j3lte** [comment]
Can you check whether or not https://github.com/j3lte/node-ifttt-maker/releases/tag/v0.1.2 helps?
